### ISSUE TITLE
Remove staic image from main page for Admin selection

### ISSUE THREAD

**Issue by paulalting** [trombastic/PyScada#24]
On the main page where one can select the application views as well as Admin functions, there is a static image loaded under the Admin title that should be removed.
It shows details for Martin.

I went into the directory and renamed this file so it no longer loads, but this is not the best solution, as it still tries to load the image and fails with broken link reference, but does look better.

I don't see any reason for an image to be shown for Admin menu selection.

**Comment by trombastic** [comment]
Dear Paul,

you are right regarding the objection that the current image shows details on my test setup, i choose to have a image there because i thought it is easier for the user to distinct between the different views and the admin link, but maybe it is better to have either no image ore a more general one. I will think about it and change it in the next release.

best wishes,
Martin

**Comment by paulalting** [comment]
Maybe if a user has Admin privilege then the Admin link can be placed in the user menu as first item above user email, what do you think ?

**Comment by trombastic** [comment]
yes that is a good place, i will change it that way
